# Generated by Django 4.1.5 on 2023-02-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_cat',
            field=models.CharField(default='', max_length=500),
        ),
    ]
